-- SQL BASICS QUERIES -- 
/* MULTI LINE COMMENTS */
SHOW CHARACTER SET;

SHOW DATABASES;

-- CREATING DATABASES --
CREATE DATABASE STUDENT;
SHOW DATABASES;

-- DELETING DATABASES--
DROP DATABASE STUDENT;
-- OR --
DROP SCHEMA STUDENT;
SHOW DATABASES;

/* IF THE DATABASE NOT EXITS MEANS IT THROW ERROR IF WE WANT TO AVOID IT MEANS */
DROP SCHEMA IF EXISTS STUDENT;

-- USING PREVIOUS DATABASE--
USE STUDENT;

-- CREATING TABLES AND ATLEAST ONE PRIMARY KEY TO IDENTIFY THE SAME DATA  --
CREATE TABLE CLASS_A(
ID INT PRIMARY KEY,
NAME VARCHAR(10),
GPA DECIMAL (3,1)
);

-- SHOWING TABLES IN THAT SPECIFIC DATABASES --
SHOW TABLES;

-- INSERTING VALUES IN TABLE --
INSERT INTO CLASS_A VALUES(1,"allah",10.0);

-- VIEWING TABLES DATA USING SELECT COMMAND --
SELECT * FROM CLASS_A;

-- UPDATING TABLES LIKE ADDING OR REMOVING COLOUMNS --
-- ADDING COLOUMN --
ALTER TABLE CLASS_A ADD PLACE VARCHAR(100);

-- DELETING COLUMN --
ALTER TABLE CLASS_A DROP PLACE;

-- INSERTING DATA IN SPECIFIC COLUMN --
INSERT INTO CLASS_A(ID,NAME) VALUES(2,'RAHIM'); 

-- DELETING A ROW USING WHERE CONDITION --
DELETE FROM CLASS_A WHERE GPA=5.2;

    SELECT id, IF (select 
    case 
    when correct_answer = given_answer then 'correct'
    when correct_answer <> given_answer then 'incorrect'
    else 'no answer'
    end) AS checks
    FROM answers
    ORDER BY id;
